# Generated by Django 5.2 on 2025-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_filedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='views',
            field=models.CharField(max_length=128),
        ),
    ]
